2021-02-07T17:45:31.108473+0300 | ERROR | Помилка в connection_func: 2003: Can't connect to MySQL server on 'locralhost:3306' (11001 getaddrinfo failed)
2021-02-07T17:46:03.282550+0300 | ERROR | An error has been caught in function 'welcome', process 'MainProcess' (1624), thread 'WorkerThread2' (15616):
Traceback (most recent call last):

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 580, in open_connection
    addrinfos = socket.getaddrinfo(self.server_host,
                |      |           |    -> 'locralhost'
                |      |           -> <mysql.connector.network.MySQLTCPSocket object at 0x0000020BCA1D8BE0>
                |      -> <function getaddrinfo at 0x0000020BC774FF70>
                -> <module 'socket' from 'C:\\Users\\38063\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socket.py'>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               |       |           |     |     |       |     |      -> 0
               |       |           |     |     |       |     -> 6
               |       |           |     |     |       -> <SocketKind.SOCK_STREAM: 1>
               |       |           |     |     -> 0
               |       |           |     -> 3306
               |       |           -> 'locralhost'
               |       -> <built-in function getaddrinfo>
               -> <module '_socket' from 'C:\\Users\\38063\\AppData\\Local\\Programs\\Python\\Python39\\DLLs\\_socket.pyd'>

socket.gaierror: [Errno 11001] getaddrinfo failed


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x0000020BC76EE790>
    -> <WorkerThread(WorkerThread2, started daemon 15616)>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
    |    -> <function WorkerThread.run at 0x0000020BC9D929D0>
    -> <WorkerThread(WorkerThread2, started daemon 15616)>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
    |     |       -> {}
    |     -> (<telebot.types.Message object at 0x0000020BCA1C5790>,)
    -> <function welcome at 0x0000020BCA1BD160>

> File "D:\Programming\python\sp_ua\sp_ua\bot_storage.py", line 102, in welcome
    conn = connection_func()
           -> <function connection_func at 0x0000020BCA1A7CA0>

  File "D:\Programming\python\sp_ua\sp_ua\bot_storage.py", line 33, in connection_func
    conn = mysql.connector.connect(host='locralhost',
           |     |         -> <function connect at 0x0000020BC914D430>
           |     -> <module 'mysql.connector' from 'C:\\Users\\38063\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\mysql\\conn...
           -> <module 'mysql' from 'C:\\Users\\38063\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\mysql\\__init__.py'>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\__init__.py", line 278, in connect
    return MySQLConnection(*args, **kwargs)
           |                |       -> {'host': 'locralhost', 'database': 'sp_ua_test', 'user': 'root', 'password': 'admin'}
           |                -> ()
           -> <class 'mysql.connector.connection.MySQLConnection'>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 108, in __init__
    self.connect(**kwargs)
    |    |         -> {'host': 'locralhost', 'database': 'sp_ua_test', 'user': 'root', 'password': 'admin'}
    |    -> <function MySQLConnectionAbstract.connect at 0x0000020BC9121EE0>
    -> <mysql.connector.connection.MySQLConnection object at 0x0000020BCA1D8C70>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\abstracts.py", line 1003, in connect
    self._open_connection()
    |    -> <function MySQLConnection._open_connection at 0x0000020BC914C550>
    -> <mysql.connector.connection.MySQLConnection object at 0x0000020BCA1D8C70>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\connection.py", line 351, in _open_connection
    self._socket.open_connection()
    |    -> None
    -> <mysql.connector.connection.MySQLConnection object at 0x0000020BCA1D8C70>

  File "C:\Users\38063\AppData\Local\Programs\Python\Python39\lib\site-packages\mysql\connector\network.py", line 598, in open_connection
    raise errors.InterfaceError(
          |      -> <class 'mysql.connector.errors.InterfaceError'>
          -> <module 'mysql.connector.errors' from 'C:\\Users\\38063\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\mysq...

mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'locralhost:3306' (11001 getaddrinfo failed)
2021-02-07T17:47:20.339539+0300 | ERROR | Помилка в connection_func: 2003: Can't connect to MySQL server on 'locralhost:3306' (11001 getaddrinfo failed)
2021-02-07T17:55:47.407562+0300 | ERROR | Помилка в connection_func: 2003: Can't connect to MySQL server on 'locralhost:3306' (11001 getaddrinfo failed)
2021-02-07T17:58:37.660872+0300 | DEBUG | ['Склад Дімона']
2021-02-07T17:58:58.352974+0300 | DEBUG | ['Склад', 'Дімона']
2021-02-07T18:00:25.321621+0300 | DEBUG | ['Склад', 'Дімона']
2021-02-07T18:01:46.769535+0300 | DEBUG | ['Склад', 'Дімона']
2021-02-07T18:01:49.564595+0300 | DEBUG | ['Склад', 'Владоса']
2021-02-07T18:41:34.095636+0300 | DEBUG | ['category', 'stickers']
2021-02-07T19:20:33.630503+0300 | DEBUG | lamps_dima
2021-02-07T19:20:33.630503+0300 | DEBUG | 1
2021-02-07T19:20:33.630503+0300 | DEBUG | ('Милый во франксе',)
2021-02-07T19:20:33.631501+0300 | DEBUG | stickers_dima
2021-02-07T19:20:33.631501+0300 | DEBUG | 31
2021-02-07T19:20:33.631501+0300 | DEBUG | ('Хуй',)
2021-02-07T19:20:33.731445+0300 | DEBUG | stickers_dima
2021-02-07T19:20:33.731445+0300 | DEBUG | 31
2021-02-07T19:20:33.731445+0300 | DEBUG | ('Хуй',)
2021-02-07T19:20:33.732445+0300 | DEBUG | lamps_dima
2021-02-07T19:20:33.732445+0300 | DEBUG | 2
2021-02-07T19:20:33.732445+0300 | DEBUG | ('Итачи',)
2021-02-07T19:23:06.702501+0300 | DEBUG | Ведмідь
2021-02-09T19:18:11.222687+0300 | DEBUG | 123
2021-02-09T19:18:27.462235+0300 | DEBUG | 4
2021-02-09T19:18:27.463232+0300 | DEBUG | <class 'str'>
2021-02-09T19:34:17.942254+0300 | DEBUG | (950, 60, 'instagram', '20450341421813', 'sent', datetime.datetime(2021, 2, 3, 11, 14, 32), 'vlad')
2021-02-09T19:34:40.441179+0300 | DEBUG | ('vlad', 950, 'instagram', 60)
2021-02-09T19:36:10.678863+0300 | DEBUG | ('vlad', 950, 'instagram', 60)
2021-02-09T19:36:10.680860+0300 | DEBUG | ('Программирование',)
2021-02-09T19:36:35.951084+0300 | DEBUG | ('vlad', 950, 'instagram', 60)
2021-02-09T19:36:35.953078+0300 | DEBUG | ('Программирование',)
2021-02-09T19:38:07.593185+0300 | DEBUG | ('vlad', 950, 'instagram', 60, datetime.datetime(2021, 2, 3, 11, 14, 32))
2021-02-09T19:38:07.594224+0300 | DEBUG | ('Программирование',)
2021-02-09T19:38:23.123317+0300 | DEBUG | ('vlad', 950, 'instagram', 60, datetime.datetime(2021, 2, 3, 11, 14, 32))
2021-02-09T19:38:23.124314+0300 | DEBUG | ('Программирование',)
2021-02-09T19:38:49.481196+0300 | DEBUG | ('vlad', 950, 'instagram', 60, datetime.datetime(2021, 2, 3, 11, 14, 32))
2021-02-09T19:38:49.481196+0300 | DEBUG | 60
2021-02-09T19:38:49.482194+0300 | DEBUG | ('Программирование',)
2021-02-09T19:39:12.717565+0300 | DEBUG | ('vlad', 950, 'instagram', 60, datetime.datetime(2021, 2, 3, 11, 14, 32))
2021-02-09T19:39:12.718564+0300 | DEBUG | 2021-02-03 11:14:32
2021-02-09T19:39:12.719561+0300 | DEBUG | ('Программирование',)
2021-02-09T19:39:58.192146+0300 | DEBUG | ('vlad', 950, 'instagram', 60, datetime.datetime(2021, 2, 3, 11, 14, 32))
2021-02-09T19:39:58.201807+0300 | DEBUG | 2021-02-03 11:14:32
2021-02-09T19:39:58.203804+0300 | DEBUG | ('Программирование',)
2021-02-09T19:58:52.766399+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T19:59:10.670144+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T19:59:23.012170+0300 | DEBUG | None
2021-02-09T20:03:50.659428+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:05:52.732126+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:06:53.448251+0300 | DEBUG | 000
2021-02-09T20:06:53.484146+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:08:03.140277+0300 | DEBUG | 0
2021-02-09T20:08:03.155370+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:10:37.673643+0300 | DEBUG | 1
2021-02-09T20:10:37.689603+0300 | DEBUG | None
2021-02-09T20:10:43.108937+0300 | DEBUG | 1
2021-02-09T20:10:43.122900+0300 | DEBUG | None
2021-02-09T20:10:46.137141+0300 | DEBUG | 0
2021-02-09T20:10:46.153123+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:12:08.164110+0300 | DEBUG | 0
2021-02-09T20:12:08.179069+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:12:08.179069+0300 | ERROR | Помилка в search_by_ttn_handler: Unread result found
2021-02-09T20:15:14.714345+0300 | DEBUG | 0
2021-02-09T20:15:14.733368+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:15:14.734367+0300 | DEBUG | ('Кіберпанк',)
2021-02-09T20:15:24.270437+0300 | DEBUG | 000
2021-02-09T20:15:24.284400+0300 | DEBUG | ('dima', 957, 'instagram', None, datetime.datetime(2021, 2, 5, 11, 42, 44))
2021-02-09T20:15:24.285397+0300 | DEBUG | ('Кіберпанк',)
2021-02-09T20:15:35.653189+0300 | DEBUG | 1
2021-02-09T20:15:35.667151+0300 | DEBUG | None
2021-02-13T19:51:15.251769+0300 | DEBUG | ('Кіберпанк',)
2021-02-13T19:51:15.263500+0300 | DEBUG | ('Клинок',)
2021-02-13T19:54:38.263654+0300 | ERROR | Помилка в delete_order_by_number: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
